[package]

name = "js"
version = "0.1.0"
authors = ["The Servo Project Developers"]

build = "build.rs"

[features]
debugmozjs = ['mozjs-sys/debugmozjs']

[dependencies.mozjs-sys]

git = "https://github.com/servo/mozjs"

[dependencies]
libc = "*"
